#!/usr/bin/env python3
"""Generate shared SVG and Android vectors from Hungii's original path geometry."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
G = json.loads((ROOT / 'assets/brand/geometry.json').read_text())
MARK, RED, INK = G['mark'], G['crimson'], G['ink']
ANDROID = 'android-prototype/app/src/main/res/'
outputs = {}

def put(path, text):
    outputs[path] = text + '\n'

def svg(viewbox, body, title='Hungii'):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" role="img" aria-label="{title}">{body}</svg>'

word = f'<g fill="{RED}" fill-rule="evenodd"><path transform="scale(.5)" d="{MARK}"/>' + ''.join(f'<path d="{p}"/>' for p in G['letters']) + '</g>'
put('assets/brand/mark.svg', svg('0 0 192 256', f'<path fill="{RED}" d="{MARK}"/>'))
put('assets/brand/wordmark.svg', svg('0 0 370 164', word))
# A square site/GitHub icon; Android supplies its own launcher mask.
put('assets/icon.svg', svg('0 0 108 108', f'<rect width="108" height="108" rx="24" fill="{INK}"/><path fill="{RED}" transform="translate(27.81 19.71) scale(.27)" d="{MARK}"/>'))

def vector(width, height, viewwidth, viewheight, content):
    return f'<?xml version="1.0" encoding="utf-8"?>\n<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{width}dp" android:height="{height}dp" android:viewportWidth="{viewwidth}" android:viewportHeight="{viewheight}">{content}</vector>'

def path(data, color=RED):
    return f'<path android:fillColor="{color}" android:fillType="evenOdd" android:pathData="{data}"/>'

launcher_group = '<group android:translateX="27.81" android:translateY="19.71" android:scaleX="0.27" android:scaleY="0.27">'
put(ANDROID+'drawable/ic_hungii_mark.xml', vector(192, 256, 192, 256, path(MARK)))
put(ANDROID+'drawable/ic_hungii_wordmark.xml', vector(370, 164, 370, 164, '<group android:scaleX="0.5" android:scaleY="0.5">'+path(MARK)+'</group>'+''.join(path(p) for p in G['letters'])))
put(ANDROID+'drawable/ic_launcher_foreground.xml', vector(108, 108, 108, 108, launcher_group+path(MARK)+'</group>'))
put(ANDROID+'drawable/ic_launcher_monochrome.xml', vector(108, 108, 108, 108, launcher_group+path(MARK, '#FFFFFF')+'</group>'))
put(ANDROID+'drawable/ic_launcher.xml', vector(108, 108, 108, 108, path('M0 0 H108 V108 H0 Z', INK)+launcher_group+path(MARK)+'</group>'))
put(ANDROID+'values/brand_colors.xml', f'<?xml version="1.0" encoding="utf-8"?>\n<resources><color name="hungii_icon_background">{INK}</color></resources>')
for api in (26, 33):
    mono = '<monochrome android:drawable="@drawable/ic_launcher_monochrome"/>' if api >= 33 else ''
    put(ANDROID+f'mipmap-anydpi-v{api}/ic_launcher.xml', '<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android"><background android:drawable="@color/hungii_icon_background"/><foreground android:drawable="@drawable/ic_launcher_foreground"/>'+mono+'</adaptive-icon>')
# Self-contained branding for broker HTML, without a network image request.
put('supabase/functions/_shared/brand.ts', '// Generated by scripts/generate-brand.py; edit assets/brand/geometry.json.\nexport const BRAND_WORDMARK = '+json.dumps(svg('0 0 370 164', word).replace('role="img"', 'width="160" height="71" role="img"'))+';')

# Review board uses the same geometry and adaptive-icon proportions.
board = ['<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="740" viewBox="0 0 1200 740"><rect width="1200" height="740" fill="#09090C"/><text x="64" y="74" fill="#FFF2F5" font-family="sans-serif" font-size="28">Hungii · one continuous fork-h</text><g transform="translate(60 140) scale(1.7)">'+word+'</g>']
for i, (bg, fg, label, shape) in enumerate([
    ('#171319', RED, 'Crimson / squircle', 'rect'),
    ('#171319', RED, 'Crimson / circle', 'circle'),
    ('#E9DBEE', '#51435C', 'Themed / light', 'circle'),
    ('#413046', '#F0DFF3', 'Themed / dark', 'circle'),
]):
    board.append(f'<g transform="translate({64+i*286} 455)">')
    board.append(f'<circle cx="94" cy="94" r="94" fill="{bg}"/>' if shape == 'circle' else f'<rect width="188" height="188" rx="46" fill="{bg}"/>')
    board.append(f'<path transform="translate(25.6 4.46) scale(.705)" fill="{fg}" d="{MARK}"/><text x="0" y="226" fill="#B8ABB4" font-family="sans-serif" font-size="17">{label}</text></g>')
board.append('</svg>')
put('assets/brand/preview.svg', ''.join(board))

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for relative, text in outputs.items():
    p = ROOT / relative
    if args.check:
        if not p.exists() or p.read_text() != text:
            raise SystemExit(f'Brand output differs: {relative}; run scripts/generate-brand.py')
    else:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
print(f'{"Checked" if args.check else "Generated"} {len(outputs)} brand assets.')
